# edition                      = "2021"
# unstable_features            = true
# brace_style                  = "AlwaysNextLine"
# control_brace_style          = "AlwaysNextLine"
# wrap_comments                = true
# fn_single_line               = false
# force_multiline_blocks       = true
# imports_granularity          = "Crate"
# overflow_delimited_expr      = true
# where_single_line            = true
# empty_item_single_line       = false
# enum_discrim_align_threshold = 40
# format_code_in_doc_comments  = true
# imports_indent               = "Visual"
# indent_style                 = "Visual"
# reorder_impl_items           = true
# struct_field_align_threshold = 40
# struct_lit_single_line       = false
# trailing_comma               = "Never"
# use_field_init_shorthand     = true
# blank_lines_upper_bound      = 1
# fn_params_layout             = "Tall"
# max_width                    = 160
# format_strings               = true
# group_imports                = "StdExternalCrate"
# comment_width                = 120
# use_small_heuristics         = "Max"
# hard_tabs                    = true
# ignore                       = ["target/", "gen/"]
